export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const ADD_CART_ITEM_FAILED = 'ADD_CART_ITEM_FAILED';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REMOVE_CART_ITEM_FAILED = 'REMOVE_CART_ITEM_FAILED';
export const GET_INITIAL_STATE = 'GET_INITIAL_STATE';
export const HIDRATE_INITIAL_STATE = 'HIDRATE_INITIAL_STATE';
